### ISSUE TITLE
checking ticket on entry

### ISSUE THREAD

**Issue by miakh** [rawen-dev/ticketonline#19]
based on qr code in ticket show information about ticket

**Comment by Pavelvicha** [comment]
QR kód je na vstupence, kterou účastník ukáže při vstupu.
QR kód by mohl odkazovat na databázi a zobrazit např. zelené pole, pokud bude záznam nalezen v db a platba bude v pořádku. Pokud nebude qr link nalezen v db a nebo platba nebude úplná nebo půjde o stornovaný lístek, zobrazit červené pole s komentářem
